version: 0.0.1
os: linux
files:
  - source: /
    destination: /home/ubuntu/Sites/ngine
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  # BeforeInstall:
  #   - location: scripts/before_install.sh
  #     timeout: 300
  #     runas: ubuntu
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu