# image: atlassian/default-image:2
image: nikolaik/python-nodejs

pipelines:
  branches:
    release:
      - step:
          caches:
            - node
          name: Build and deploy to S3
          script:
            - npm install
            - echo $ENV_ENCODED | base64 -d > .env
            - npm run build
            - pip install awscli --upgrade --ignore-installed six
            - aws s3 sync ./build s3://$PRODUCTION_BUCKET_NAME/
            - aws s3 cp --cache-control max-age=0 ./build/service-worker.js s3://$PRODUCTION_BUCKET_NAME/
  pull-requests:
    "**":
      - step:
          name: Installing & Running Test
          caches:
            - node
          script:
            - rm -rf package-lock.json
            - rm -rf node_modules
            - npm install
            - npm run test:nowatch
      - step:
          name: Code linting
          script:
            - npm install
            - npm run lint
          caches:
            - node